spring.application.name=CineMate
spring.data.mongodb.uri=mongodb://root:deinPasswort@localhost:27017/cinemate?authSource=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=deinPasswort
spring.data.mongodb.database=cinemate
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=TRACE
spring.mvc.log-request-details=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.mvc.contentnegotiation.media-types.json=application/json
