spring.application.name=CineMate
spring.data.mongodb.uri=mongodb://root:deinPasswort@localhost:27017/cinemate?authSource=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=deinPasswort
spring.data.mongodb.database=cinemate
# spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG

