POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "maxi",
  "password": "1234567"
}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
"username": "maxi",
"password": "1234567",
  "email": "maxi@gmail.com",
  "bio": "Wuzz up"
}
###
PUT http://localhost:8080/api/users/6813a9c6a70428033d933986
Content-Type: application/json

{
  "avatarUrl": "https://api.dicebear.com/7.x/bottts/svg?seed=USERNAME"
}

###
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXhpIiwiZXhwIjoxNzQ1MDQyNDQzLCJpYXQiOjE3NDUwMDY0NDN9.60VPYsuNHIDfF5SULKNZVh-dEkq7yE444Stq0TUGyjE

###
GET http://localhost:8080/api/users
###

DELETE http://localhost:8080/api/users/6813a8eaf4f96f556a24061b

###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Inception",
  "description": "Ein Dieb, der Informationen aus Träumen stiehlt, erhält die Aufgabe, eine Idee einzupflanzen.",
  "genre": "Sci-Fi",
  "releaseDate": "2010-07-16",
  "duration": "2h 28m",
  "posterUrl": "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg"
}

###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "The Dark Knight",
  "description": "Batman stellt sich dem Joker, einem kriminellen Genie, das Chaos über Gotham bringen will.",
  "genre": "Action",
  "releaseDate": "2008-07-18",
  "duration": "2h 32m",
  "posterUrl": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg"
}

###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Interstellar",
  "description": "Ein Team von Forschern reist durch ein Wurmloch im Weltraum auf der Suche nach einer neuen Heimat für die Menschheit.",
  "genre": "Sci-Fi",
  "releaseDate": "2014-11-07",
  "duration": "2h 49m",
  "posterUrl": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"
}

###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Fight Club",
  "description": "Ein gelangweilter Büroarbeiter gründet mit einem Seifenverkäufer einen geheimen Fight Club.",
  "genre": "Drama",
  "releaseDate": "1999-10-15",
  "duration": "2h 19m",
  "posterUrl": "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg"
}
###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Avengers: Dommsday",
  "description": "Nicht verfügbar",
  "genre": "Action",
  "releaseDate": "2026-05-01",
  "duration": "2h",
  "posterUrl": "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6eB2oh1SplddsZYCdayrIdrIGLd.jpg"
}
###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Avengers: Secret Wars",
  "description": "Nicht verfügbar",
  "genre": "Action",
  "releaseDate": "2027-05-05",
  "duration": "2h",
  "posterUrl": "https://media.themoviedb.org/t/p/w300_and_h450_bestv2/f0YBuh4hyiAheXhh4JnJWoKi9g5.jpg"
}

###
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "The Matrix",
  "description": "Ein Hacker entdeckt die Wahrheit über seine Realität und seine Rolle im Krieg gegen ihre Kontrolleure.",
  "genre": "Sci-Fi",
  "releaseDate": "1999-03-31",
  "duration": "2h 16m",
  "posterUrl": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg"
}

###
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/reviews/user/6813a9c6a70428033d933986

###
DELETE http://localhost:8080/api/movies/67fd6c6db9c65836190d6085

###
PUT http://localhost:8080/api/movies/67fd6c67b9c65836190d6082
Content-Type: application/json

{

  "posterUrl": "https://image.tmdb.org/t/p/w500/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg"
}

###
GET http://localhost:8080/api/users/6813a9c6a70428033d933986/watchlist/movies

###
PUT http://localhost:8080/api/users/6813a9c6a70428033d933986/watchlist/movies/680e7b0923c0b14c9c4811b9
Content-Type: application/json

###
PUT http://localhost:8080/api/users/6813a9c6a70428033d933986/watchlist/series/680bdb533ee10e7e79fa82b3
Content-Type: application/json

###
GET http://localhost:8080/api/users/6813a9c6a70428033d933986/watchlist/series

###
DELETE http://localhost:8080/api/users/67fd70fdf86b765965cfa2cb/watchlist/67fd703bf86b765965cfa2c5

###
GET http://localhost:8080/api/users

###
POST http://localhost:8080/api/series
Content-Type: application/json

{
  "title": "Stranger Things",
  "description": "Eine Gruppe von Kindern entdeckt übernatürliche Ereignisse und geheime Experimente in ihrer Kleinstadt.",
  "genre": "Mystery, Sci-Fi, Horror",
  "releaseDate": "2016-07-15",
  "posterUrl": "https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
  "seasons": [
    {
      "seasonNumber": 1,
      "episodes": [
        {
          "episodeNumber": 1,
          "title": "Chapter One: The Vanishing of Will Byers",
          "duration": "47m",
          "releaseDate": "2016-07-15T00:00:00.000+00:00",
          "description": "Will Byers verschwindet spurlos. Seine Freunde suchen ihn und stoßen dabei auf ein mysteriöses Mädchen.",
          "posterUrl": "https://image.tmdb.org/t/p/original/AdwF2jXvhdODr6gUZ61bHKRkz09.jpg"
        },
        {
          "episodeNumber": 2,
          "title": "Chapter Two: The Weirdo on Maple Street",
          "duration": "55m",
          "releaseDate": "2016-07-15T00:00:00.000+00:00",
          "description": "Die Jungen verstecken das Mädchen, das offenbar übernatürliche Kräfte besitzt.",
          "posterUrl": "https://image.tmdb.org/t/p/original/8iA56ugQyHZmX81wSsNqwXjCE6F.jpg"
        },
        {
          "episodeNumber": 3,
          "title": "Chapter Three: Holly, Jolly",
          "duration": "51m",
          "releaseDate": "2016-07-15T00:00:00.000+00:00",
          "description": "Joyce glaubt, dass Will ihr über Lichter Signale sendet. Nancy sucht ihre verschwundene Freundin Barb.",
          "posterUrl": "https://image.tmdb.org/t/p/original/5snULpWQWp7aqFto7UbRcEkEyyS.jpg"
        }
      ]
    }
  ]
}
###

POST http://localhost:8080/api/series
Content-Type: application/json

{
  "title": "Breaking Bad",
  "description": "Ein Chemielehrer wird zum Drogenkoch, um seine Familie zu versorgen.",
  "genre": "Drama",
  "releaseDate": "2008-01-20",
  "duration": "47m",
  "posterUrl": "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg"
}

###
POST http://localhost:8080/api/series
Content-Type: application/json

{
  "title": "The Office",
  "description": "Das Leben in einem Büro voller skurriler Kollegen – humorvoll und charmant.",
  "genre": "Comedy",
  "releaseDate": "2005-03-24",
  "duration": "22m",
  "posterUrl": "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg"
}

###
POST http://localhost:8080/api/series
Content-Type: application/json

{
  "title": "The Witcher",
  "description": "Ein Monsterjäger kämpft gegen dunkle Magie und politische Intrigen.",
  "genre": "Fantasy",
  "releaseDate": "2019-12-20",
  "duration": "1h",
  "posterUrl": "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg"
}

###
POST http://localhost:8080/api/reviews/movie/680e7b0723c0b14c9c4811b8/680fb9bf040ad6445d9d4ef7
Content-Type: application/json

{
  "rating": 4,
  "comment": "Ein fantastischer Film!",
  "type": "movie"
}

###
GET http://localhost:8080/api/movies

###

POST http://localhost:8080/api/reviews/movie/680e7b0923c0b14c9c4811b9/680fb9bf040ad6445d9d4ef7
Content-Type: application/json

{
  "rating": 4,
  "comment": "Ein fantastischer Film!",
  "type": "movie"
}
